---

- hosts: all
  become: yes
  become_method: sudo
  vars_files:
   - secrets.yml # Contains private ssh keys for things like qps script.
  roles:
   - software-tools
   - cloud-credentials 
   - install-kubectl 
   - install-helm
